### PR TITLE
License and System

### PR DESCRIPTION
**Pull request by jbrockopp**

### CODE REVIEW

**Comment by jbrockopp** [comment]
@lusis I'm going to be adding more... but figured I would split over several prs.

**Comment by jbrockopp** [comment]
@lusis sorry to bug ya but I have other stuff I will be adding once this PR gets merged. Any ETA on when this will be merged?

**Comment by lusis** [comment]
Sorry was slammed with hurricanes and storms and such. Lemme ping you back on this in a few.

**Comment by jbrockopp** [comment]
@lusis I'm sorry to hear that :( Hope you got out safe and your stuff didn't take too much damage

**Comment by lusis** [comment]
@jbrockopp all is well. Mainly just had no power for a few days and lots of work to catch up on. Merging and thanks so much!

**Pull request merged**
